### ISSUE TITLE
error compiled

### ISSUE THREAD

**Issue by riskiana** [mifosio/identity#10]
AuthenticationCommandHandler.java:184: error:
method deserialize in class TenantRefreshTokenSerializer cannot be applied to gi
ven types;
        tenantRefreshTokenSerializer.deserialize(command.getRefreshToken());
                                    ^
  required: TenantApplicationRsaKeyProvider,String
  found: String
  reason: actual and formal argument lists differ in length
TenantService.java:37: error: TenantService is not abs
tract and does not override abstract method getLatestApplicationSigningKeyPair()
 in TenantSignatureRepository
public class TenantService implements TenantSignatureRepository {
       ^
2 errors

**Comment by myrle-krantz** [comment]
There were complementary changes in anubis and identity, and since we're not versioning yet I couldn't reference the newest version.  Please pull both projects and retry.
